nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Link']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': # toutes les routes de ton API
            allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173'] # ton front Vue.js
            allow_headers: ['Content-Type', 'Authorization', 'Accept']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
